name: Test Build

on:
  workflow_dispatch:  # 只允许手动触发
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest

jobs:
  test-build:
    runs-on: ${{ github.event.inputs.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies (Ubuntu)
      if: github.event.inputs.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Prepare build environment
      run: python prepare_build.py

    - name: Build executable
      run: pyinstaller HeadAlignmentTool.spec --clean --noconfirm

    - name: Test executable exists
      run: python -c "import os; print('✅ Build completed!' if (os.path.exists('dist/HeadAlignmentTool') or os.path.exists('dist/HeadAlignmentTool.exe')) else '❌ Executable not found'); [print(f'  - {item}') for item in os.listdir('dist')] if os.path.exists('dist') else None"

    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-build-${{ github.event.inputs.platform }}
        path: dist/HeadAlignmentTool*
        retention-days: 7 